/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/modal-gallery.module';
import * as import2 from '@angular/common';
class AngularModalGalleryModuleInjector extends import0.ɵNgModuleInjector<import1.AngularModalGalleryModule> {
  _CommonModule_0:import2.CommonModule;
  _AngularModalGalleryModule_1:import1.AngularModalGalleryModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.AngularModalGalleryModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._AngularModalGalleryModule_1 = new import1.AngularModalGalleryModule();
    return this._AngularModalGalleryModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.AngularModalGalleryModule)) { return this._AngularModalGalleryModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularModalGalleryModuleNgFactory:import0.NgModuleFactory<import1.AngularModalGalleryModule> = new import0.NgModuleFactory<any>(AngularModalGalleryModuleInjector,import1.AngularModalGalleryModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2tzODkvZ2l0L2FuZ3VsYXItbW9kYWwtZ2FsbGVyeS9zcmMvbW9kYWwtZ2FsbGVyeS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMva3M4OS9naXQvYW5ndWxhci1tb2RhbC1nYWxsZXJ5L3NyYy9tb2RhbC1nYWxsZXJ5Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
