/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../index';
import * as import2 from '@angular/common';
import * as import3 from '../src/modal-gallery.module';
import * as import4 from '../src/components/keyboard.service';
class AngularRootModalGalleryModuleInjector extends import0.ɵNgModuleInjector<import1.AngularRootModalGalleryModule> {
  _CommonModule_0:import2.CommonModule;
  _AngularModalGalleryModule_1:import3.AngularModalGalleryModule;
  _AngularRootModalGalleryModule_2:import1.AngularRootModalGalleryModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  __KeyboardService_4:import4.KeyboardService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  get _KeyboardService_4():import4.KeyboardService {
    if ((this.__KeyboardService_4 == null)) { (this.__KeyboardService_4 = new import4.KeyboardService()); }
    return this.__KeyboardService_4;
  }
  createInternal():import1.AngularRootModalGalleryModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._AngularModalGalleryModule_1 = new import3.AngularModalGalleryModule();
    this._AngularRootModalGalleryModule_2 = new import1.AngularRootModalGalleryModule();
    return this._AngularRootModalGalleryModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.AngularModalGalleryModule)) { return this._AngularModalGalleryModule_1; }
    if ((token === import1.AngularRootModalGalleryModule)) { return this._AngularRootModalGalleryModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import4.KeyboardService)) { return this._KeyboardService_4; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularRootModalGalleryModuleNgFactory:import0.NgModuleFactory<import1.AngularRootModalGalleryModule> = new import0.NgModuleFactory<any>(AngularRootModalGalleryModuleInjector,import1.AngularRootModalGalleryModule);
class ModalGalleryModuleInjector extends import0.ɵNgModuleInjector<import1.ModalGalleryModule> {
  _CommonModule_0:import2.CommonModule;
  _AngularModalGalleryModule_1:import3.AngularModalGalleryModule;
  _ModalGalleryModule_2:import1.ModalGalleryModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  createInternal():import1.ModalGalleryModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._AngularModalGalleryModule_1 = new import3.AngularModalGalleryModule();
    this._ModalGalleryModule_2 = new import1.ModalGalleryModule();
    return this._ModalGalleryModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.AngularModalGalleryModule)) { return this._AngularModalGalleryModule_1; }
    if ((token === import1.ModalGalleryModule)) { return this._ModalGalleryModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ModalGalleryModuleNgFactory:import0.NgModuleFactory<import1.ModalGalleryModule> = new import0.NgModuleFactory<any>(ModalGalleryModuleInjector,import1.ModalGalleryModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2tzODkvZ2l0L2FuZ3VsYXItbW9kYWwtZ2FsbGVyeS9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9rczg5L2dpdC9hbmd1bGFyLW1vZGFsLWdhbGxlcnkvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
